all:
  children:
    proxmox:
      hosts:
        pve-core:
          ansible_host: 10.1.20.10
        pve-dmz:
          ansible_host: 10.1.20.11
    servers:
      hosts:
        ubuntu-server:
          ansible_host: 10.1.20.100
        mailcow:
          ansible_host: 10.1.30.50
